# Generated by Django 4.0.4 on 2022-04-24 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('guidance_id', models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='текст рекоммендации')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Guidance',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('content', models.TextField(verbose_name='описание')),
                ('photo_file', models.ImageField(upload_to='images/', verbose_name='изображение')),
                ('slug', models.SlugField(max_length=255, verbose_name='краткое наименование')),
                ('diaphragm', models.CharField(blank=True, default='', max_length=10, verbose_name='диафрагма')),
                ('exposure', models.CharField(blank=True, default='', max_length=10, verbose_name='выдержка')),
                ('iso', models.CharField(blank=True, default='', max_length=10, verbose_name='ISO')),
                ('raiting_light', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True, verbose_name='рейтинг свет')),
                ('raiting_focus', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True, verbose_name='рейтинг фокус')),
                ('raiting_composition', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True, verbose_name='рейтинг композиция')),
                ('raiting_result', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True, verbose_name='итоговый рейтинг')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('guidance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.guidance')),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Photos',
                'ordering': ['-published_date'],
            },
        ),
        migrations.AddField(
            model_name='guidance',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tags'),
        ),
    ]
